# Uncomment the next line to define a global platform for your project
 platform :ios, '10.1'
use_frameworks!

target 'Election' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

pod 'SwiftKeychainWrapper', '~> 3.2'



  # Pods for Election

  target 'ElectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ElectionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
